name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
  schedule:
    # Run once a year
    - cron: 0 0 1 7 *

jobs:
  build:
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        cargo_opts: ["", "--features=slog/dynamic-keys"]
        include:
          - rust: stable
            cargo_opts: "--release"
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ubuntu-latest
    env:
      CARGO_OPTS: ${{ matrix.cargo_opts }}
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get install libsystemd-dev
      - name: Rust toolchain
        run: |
          rustup override set ${{ matrix.rust }}
          rustup component add clippy
      - name: Build
        run: cargo build --verbose ${{ matrix.cargo_opts }}
      - name: Test
        run: cargo test --verbose ${{ matrix.cargo_opts }}
      - name: Format
        if: "matrix.rust == 'stable' && matrix.cargo_opts == ''"
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy ${{ matrix.cargo_opts }} -- -D warnings
